import nbformat
from nbformat.v4 import new_markdown_cell, new_code_cell
from pathlib import Path


def main() -> None:
    nb_path = Path("main.ipynb")
    nb = nbformat.read(nb_path, as_version=4)

    marker = "## Actividad 9 - Comparacion del mejor SVM contra modelos de hojas anteriores"
    all_md = "\n".join(
        "".join(c.get("source", "")) for c in nb.cells if c.get("cell_type") == "markdown"
    )
    if marker in all_md:
        print("Activity 9 already exists. No changes made.")
        return

    md = new_markdown_cell(
        "---\n"
        "## Actividad 9 - Comparacion del mejor SVM contra modelos de hojas anteriores\n\n"
        "Se compara el mejor SVM con algoritmos usados en hojas anteriores (Arbol de decision, Random Forest, Naive Bayes, KNN y Regresion Logistica) usando la misma variable respuesta multiclase (`barata`, `media`, `cara`).\n\n"
        "Criterios de comparacion:\n"
        "- Efectividad: `accuracy` y `F1-macro` en test.\n"
        "- Eficiencia: tiempo de entrenamiento (`fit`) y tiempo de prediccion (`predict`)."
    )

    code = new_code_cell(
        "# 9.1 Comparacion de efectividad y tiempo de procesamiento\n"
        "import time\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "from scipy import sparse\n"
        "from sklearn.compose import ColumnTransformer\n"
        "from sklearn.impute import SimpleImputer\n"
        "from sklearn.metrics import accuracy_score, f1_score\n"
        "from sklearn.pipeline import Pipeline\n"
        "from sklearn.preprocessing import FunctionTransformer, OneHotEncoder, StandardScaler\n"
        "from sklearn.svm import SVC\n"
        "from sklearn.tree import DecisionTreeClassifier\n"
        "from sklearn.ensemble import RandomForestClassifier\n"
        "from sklearn.naive_bayes import GaussianNB\n"
        "from sklearn.neighbors import KNeighborsClassifier\n"
        "from sklearn.linear_model import LogisticRegression\n\n"
        "def to_dense(x):\n"
        "    return x.toarray() if sparse.issparse(x) else x\n\n"
        "dense_transformer = FunctionTransformer(to_dense, accept_sparse=True)\n\n"
        "# Preprocesador para modelos basados en distancia/lineales/probabilisticos\n"
        "preprocessor_std = ColumnTransformer(\n"
        "    transformers=[\n"
        "        ('num', Pipeline([\n"
        "            ('imputer', SimpleImputer(strategy='median')),\n"
        "            ('scaler', StandardScaler()),\n"
        "        ]), num_features),\n"
        "        ('cat', Pipeline([\n"
        "            ('imputer', SimpleImputer(strategy='most_frequent')),\n"
        "            ('onehot', OneHotEncoder(handle_unknown='ignore')),\n"
        "        ]), cat_features),\n"
        "    ],\n"
        "    remainder='drop',\n"
        ")\n\n"
        "# Preprocesador para modelos de arboles (sin escalado)\n"
        "preprocessor_tree = ColumnTransformer(\n"
        "    transformers=[\n"
        "        ('num', SimpleImputer(strategy='median'), num_features),\n"
        "        ('cat', Pipeline([\n"
        "            ('imputer', SimpleImputer(strategy='most_frequent')),\n"
        "            ('onehot', OneHotEncoder(handle_unknown='ignore')),\n"
        "        ]), cat_features),\n"
        "    ],\n"
        "    remainder='drop',\n"
        ")\n\n"
        "# Se usa el mismo subset de entrenamiento utilizado en Actividad 4 para comparacion justa de tiempo\n"
        "X_tr = X_train_svm\n"
        "y_tr = y_train_svm\n"
        "X_te = X_test\n"
        "y_te = y_test_cat\n\n"
        "models = {\n"
        "    'SVM_RBF_Best': Pipeline([\n"
        "        ('prep', preprocessor_std),\n"
        "        ('clf', SVC(kernel='rbf', C=3.0, gamma='scale', decision_function_shape='ovr', random_state=42)),\n"
        "    ]),\n"
        "    'DecisionTree': Pipeline([\n"
        "        ('prep', preprocessor_tree),\n"
        "        ('clf', DecisionTreeClassifier(max_depth=15, min_samples_leaf=5, random_state=42)),\n"
        "    ]),\n"
        "    'RandomForest': Pipeline([\n"
        "        ('prep', preprocessor_tree),\n"
        "        ('clf', RandomForestClassifier(\n"
        "            n_estimators=250,\n"
        "            max_depth=None,\n"
        "            min_samples_leaf=2,\n"
        "            n_jobs=-1,\n"
        "            random_state=42,\n"
        "        )),\n"
        "    ]),\n"
        "    'NaiveBayes': Pipeline([\n"
        "        ('prep', preprocessor_std),\n"
        "        ('to_dense', dense_transformer),\n"
        "        ('clf', GaussianNB()),\n"
        "    ]),\n"
        "    'KNN': Pipeline([\n"
        "        ('prep', preprocessor_std),\n"
        "        ('to_dense', dense_transformer),\n"
        "        ('clf', KNeighborsClassifier(n_neighbors=15, weights='distance')),\n"
        "    ]),\n"
        "    'LogisticRegression': Pipeline([\n"
        "        ('prep', preprocessor_std),\n"
        "        ('clf', LogisticRegression(max_iter=2000, solver='saga', multi_class='multinomial', n_jobs=-1, random_state=42)),\n"
        "    ]),\n"
        "}\n\n"
        "results = []\n"
        "for name, model in models.items():\n"
        "    t0 = time.perf_counter()\n"
        "    model.fit(X_tr, y_tr)\n"
        "    fit_time = time.perf_counter() - t0\n\n"
        "    t1 = time.perf_counter()\n"
        "    y_pred = model.predict(X_te)\n"
        "    pred_time = time.perf_counter() - t1\n\n"
        "    results.append({\n"
        "        'modelo': name,\n"
        "        'test_acc': accuracy_score(y_te, y_pred),\n"
        "        'test_f1_macro': f1_score(y_te, y_pred, average='macro'),\n"
        "        'fit_time_sec': fit_time,\n"
        "        'predict_time_sec': pred_time,\n"
        "        'total_time_sec': fit_time + pred_time,\n"
        "    })\n\n"
        "res_df = pd.DataFrame(results).sort_values('test_f1_macro', ascending=False).reset_index(drop=True)\n"
        "res_df[['test_acc', 'test_f1_macro', 'fit_time_sec', 'predict_time_sec', 'total_time_sec']] = res_df[[\n"
        "    'test_acc', 'test_f1_macro', 'fit_time_sec', 'predict_time_sec', 'total_time_sec'\n"
        "]].round(4)\n\n"
        "print('=== Comparacion SVM vs modelos anteriores ===')\n"
        "display(res_df)\n\n"
        "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n"
        "axes[0].barh(res_df['modelo'], res_df['test_f1_macro'], color='#3498db')\n"
        "axes[0].set_title('Efectividad (F1-macro en test)')\n"
        "axes[0].set_xlim(0, 1)\n"
        "axes[0].set_xlabel('F1-macro')\n\n"
        "axes[1].barh(res_df['modelo'], res_df['total_time_sec'], color='#e67e22')\n"
        "axes[1].set_title('Tiempo total de procesamiento')\n"
        "axes[1].set_xlabel('Segundos (fit + predict)')\n\n"
        "plt.tight_layout()\n"
        "plt.show()\n\n"
        "best_predictive = res_df.iloc[0]['modelo']\n"
        "slowest_model = res_df.sort_values('total_time_sec', ascending=False).iloc[0]['modelo']\n"
        "print('Mejor modelo para predecir (F1-macro):', best_predictive)\n"
        "print('Modelo que mas se demoro en procesar:', slowest_model)"
    )

    interp = new_markdown_cell(
        "### Interpretacion Actividad 9\n\n"
        "En esta comparacion, el mejor modelo para predecir debe evaluarse principalmente con **F1-macro en test**, porque la variable respuesta es multiclase y se requiere balance entre clases. "
        "El modelo con mayor `test_f1_macro` en la tabla final se considera el mas efectivo. Por eficiencia, el modelo con mayor `total_time_sec` es el que mas se demoro en procesar. "
        "Si el mejor SVM mantiene el mejor F1-macro, entonces sigue siendo la mejor opcion predictiva; si otro algoritmo (por ejemplo Random Forest o Regresion Logistica) lo supera, conviene priorizar ese modelo. "
        "La decision final debe balancear **calidad predictiva** y **tiempo de procesamiento** segun el objetivo del laboratorio."
    )

    nb.cells.extend([md, code, interp])
    nbformat.write(nb, nb_path)
    print("Added Activity 9 cells to main.ipynb")


if __name__ == "__main__":
    main()
